apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/node-example
    context: backend
    docker:
      buildArgs:
        SCRIPT: "{{.SCRIPT_ENV}}"
    sync:
      '*.js': .
deploy:
  kubectl:
    manifests:
    - "backend/k8s/**"
